# Generated by Django 5.2.5 on 2025-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('debut_year', models.IntegerField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('debut_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
